apiVersion: v1
kind: Service
metadata:
  name: emp-backend
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "emp.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: emp-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
