apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emp-persistence-data
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "emp.labels" . | nindent 4 }}
    app.kubernetes.io/component: persistence
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.persistence.size | quote }}
