apiVersion: v1
kind: Service
metadata:
  name: emp-persistence
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "emp.labels" . | nindent 4 }}
    app.kubernetes.io/component: persistence
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.persistence.service.port }}
      targetPort: postgres
  selector:
    app.kubernetes.io/name: emp-persistence
    app.kubernetes.io/instance: {{ .Release.Name }}
