{{- $secrets := default dict .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: emp-secret
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "emp.labels" . | nindent 4 }}
type: Opaque
stringData:
  IPINFO_API_KEY: {{ required "secrets.ipinfoApiKey is required" $secrets.ipinfoApiKey | quote }}
  POSTGRES_URL: {{ .Values.backend.env.postgresUrl | quote }}
  POSTGRES_DB: {{ .Values.persistence.database.name | quote }}
  POSTGRES_USER: {{ .Values.persistence.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.persistence.database.password | quote }}
