{{- $secrets := default dict .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: emp-secret
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "emp.labels" . | nindent 4 }}
type: Opaque
stringData:
  IPINFO_API_KEY: {{ required "secrets.ipinfoApiKey is required" $secrets.ipinfoApiKey | quote }}
