CREATE TABLE COUPON (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_code VARCHAR(255),
    country_code VARCHAR(255),
    claim_limit_count INTEGER,
    claim_count INTEGER,
    created_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_coupon_coupon_code UNIQUE (coupon_code)
);

CREATE INDEX idx_coupon_coupon_code ON COUPON (coupon_code);
