spring.application.name=couponservice
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

ipinfo.api.url=https://api.ipinfo.io/lite/
ipinfo.api.key=${IPINFO_API_KEY}
ipinfo.ip.address.override=${IPINFO_IP_ADDRESS_OVERRIDE}

ipinfo.cache.maximum-size=1000
ipinfo.cache.ttl=1m

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
